//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("zera_leviModel", "fk_accounts_people1", "t_people", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataCache.t_people), "t_accounts", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataCache.t_accounts), true)]
[assembly: EdmRelationshipAttribute("zera_leviModel", "fk_donations_accounts", "t_accounts", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataCache.t_accounts), "t_donations", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataCache.t_donations), true)]
[assembly: EdmRelationshipAttribute("zera_leviModel", "fk_phone_numbers_people1", "t_people", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataCache.t_people), "t_phone_numbers", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataCache.t_phone_numbers), true)]
[assembly: EdmRelationshipAttribute("zera_leviModel", "fk_yahrtziehts_people1", "t_people", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataCache.t_people), "t_yahrtziehts", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataCache.t_yahrtziehts), true)]
[assembly: EdmRelationshipAttribute("zera_leviModel", "fk_phone_numbers_phone_types1", "t_phone_types", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataCache.t_phone_types), "t_phone_numbers", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataCache.t_phone_numbers), true)]
[assembly: EdmRelationshipAttribute("zera_leviModel", "fk_users_privilege_groups1", "t_privilege_groups", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataCache.t_privilege_groups), "t_users", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataCache.t_users), true)]
[assembly: EdmRelationshipAttribute("zera_leviModel", "t_privileges_per_group", "t_privilege_groups", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataCache.t_privilege_groups), "t_privileges", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataCache.t_privileges))]

#endregion

namespace DataCache
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class zera_leviEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new zera_leviEntities object using the connection string found in the 'zera_leviEntities' section of the application configuration file.
        /// </summary>
        public zera_leviEntities() : base("name=zera_leviEntities", "zera_leviEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new zera_leviEntities object.
        /// </summary>
        public zera_leviEntities(string connectionString) : base(connectionString, "zera_leviEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new zera_leviEntities object.
        /// </summary>
        public zera_leviEntities(EntityConnection connection) : base(connection, "zera_leviEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<t_accounts> t_accounts
        {
            get
            {
                if ((_t_accounts == null))
                {
                    _t_accounts = base.CreateObjectSet<t_accounts>("t_accounts");
                }
                return _t_accounts;
            }
        }
        private ObjectSet<t_accounts> _t_accounts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<t_donations> t_donations
        {
            get
            {
                if ((_t_donations == null))
                {
                    _t_donations = base.CreateObjectSet<t_donations>("t_donations");
                }
                return _t_donations;
            }
        }
        private ObjectSet<t_donations> _t_donations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<t_people> t_people
        {
            get
            {
                if ((_t_people == null))
                {
                    _t_people = base.CreateObjectSet<t_people>("t_people");
                }
                return _t_people;
            }
        }
        private ObjectSet<t_people> _t_people;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<t_phone_numbers> t_phone_numbers
        {
            get
            {
                if ((_t_phone_numbers == null))
                {
                    _t_phone_numbers = base.CreateObjectSet<t_phone_numbers>("t_phone_numbers");
                }
                return _t_phone_numbers;
            }
        }
        private ObjectSet<t_phone_numbers> _t_phone_numbers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<t_phone_types> t_phone_types
        {
            get
            {
                if ((_t_phone_types == null))
                {
                    _t_phone_types = base.CreateObjectSet<t_phone_types>("t_phone_types");
                }
                return _t_phone_types;
            }
        }
        private ObjectSet<t_phone_types> _t_phone_types;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<t_privilege_groups> t_privilege_groups
        {
            get
            {
                if ((_t_privilege_groups == null))
                {
                    _t_privilege_groups = base.CreateObjectSet<t_privilege_groups>("t_privilege_groups");
                }
                return _t_privilege_groups;
            }
        }
        private ObjectSet<t_privilege_groups> _t_privilege_groups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<t_privileges> t_privileges
        {
            get
            {
                if ((_t_privileges == null))
                {
                    _t_privileges = base.CreateObjectSet<t_privileges>("t_privileges");
                }
                return _t_privileges;
            }
        }
        private ObjectSet<t_privileges> _t_privileges;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<t_users> t_users
        {
            get
            {
                if ((_t_users == null))
                {
                    _t_users = base.CreateObjectSet<t_users>("t_users");
                }
                return _t_users;
            }
        }
        private ObjectSet<t_users> _t_users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<t_yahrtziehts> t_yahrtziehts
        {
            get
            {
                if ((_t_yahrtziehts == null))
                {
                    _t_yahrtziehts = base.CreateObjectSet<t_yahrtziehts>("t_yahrtziehts");
                }
                return _t_yahrtziehts;
            }
        }
        private ObjectSet<t_yahrtziehts> _t_yahrtziehts;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the t_accounts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTot_accounts(t_accounts t_accounts)
        {
            base.AddObject("t_accounts", t_accounts);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the t_donations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTot_donations(t_donations t_donations)
        {
            base.AddObject("t_donations", t_donations);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the t_people EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTot_people(t_people t_people)
        {
            base.AddObject("t_people", t_people);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the t_phone_numbers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTot_phone_numbers(t_phone_numbers t_phone_numbers)
        {
            base.AddObject("t_phone_numbers", t_phone_numbers);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the t_phone_types EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTot_phone_types(t_phone_types t_phone_types)
        {
            base.AddObject("t_phone_types", t_phone_types);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the t_privilege_groups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTot_privilege_groups(t_privilege_groups t_privilege_groups)
        {
            base.AddObject("t_privilege_groups", t_privilege_groups);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the t_privileges EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTot_privileges(t_privileges t_privileges)
        {
            base.AddObject("t_privileges", t_privileges);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the t_users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTot_users(t_users t_users)
        {
            base.AddObject("t_users", t_users);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the t_yahrtziehts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTot_yahrtziehts(t_yahrtziehts t_yahrtziehts)
        {
            base.AddObject("t_yahrtziehts", t_yahrtziehts);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public int clear_database()
        {
            return base.ExecuteFunction("clear_database");
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="zera_leviModel", Name="t_accounts")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_accounts : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new t_accounts object.
        /// </summary>
        /// <param name="c_id">Initial value of the C_id property.</param>
        /// <param name="person_id">Initial value of the person_id property.</param>
        public static t_accounts Createt_accounts(global::System.Int32 c_id, global::System.Int32 person_id)
        {
            t_accounts t_accounts = new t_accounts();
            t_accounts.C_id = c_id;
            t_accounts.person_id = person_id;
            return t_accounts;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 C_id
        {
            get
            {
                return _C_id;
            }
            set
            {
                if (_C_id != value)
                {
                    OnC_idChanging(value);
                    ReportPropertyChanging("C_id");
                    _C_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("C_id");
                    OnC_idChanged();
                }
            }
        }
        private global::System.Int32 _C_id;
        partial void OnC_idChanging(global::System.Int32 value);
        partial void OnC_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 person_id
        {
            get
            {
                return _person_id;
            }
            set
            {
                Onperson_idChanging(value);
                ReportPropertyChanging("person_id");
                _person_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("person_id");
                Onperson_idChanged();
            }
        }
        private global::System.Int32 _person_id;
        partial void Onperson_idChanging(global::System.Int32 value);
        partial void Onperson_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> monthly_total
        {
            get
            {
                return _monthly_total;
            }
            set
            {
                Onmonthly_totalChanging(value);
                ReportPropertyChanging("monthly_total");
                _monthly_total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("monthly_total");
                Onmonthly_totalChanged();
            }
        }
        private Nullable<global::System.Int32> _monthly_total;
        partial void Onmonthly_totalChanging(Nullable<global::System.Int32> value);
        partial void Onmonthly_totalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> last_month_paid
        {
            get
            {
                return _last_month_paid;
            }
            set
            {
                Onlast_month_paidChanging(value);
                ReportPropertyChanging("last_month_paid");
                _last_month_paid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("last_month_paid");
                Onlast_month_paidChanged();
            }
        }
        private Nullable<global::System.DateTime> _last_month_paid;
        partial void Onlast_month_paidChanging(Nullable<global::System.DateTime> value);
        partial void Onlast_month_paidChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("zera_leviModel", "fk_accounts_people1", "t_people")]
        public t_people t_people
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_people>("zera_leviModel.fk_accounts_people1", "t_people").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_people>("zera_leviModel.fk_accounts_people1", "t_people").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<t_people> t_peopleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_people>("zera_leviModel.fk_accounts_people1", "t_people");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<t_people>("zera_leviModel.fk_accounts_people1", "t_people", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("zera_leviModel", "fk_donations_accounts", "t_donations")]
        public EntityCollection<t_donations> t_donations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<t_donations>("zera_leviModel.fk_donations_accounts", "t_donations");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<t_donations>("zera_leviModel.fk_donations_accounts", "t_donations", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="zera_leviModel", Name="t_donations")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_donations : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new t_donations object.
        /// </summary>
        /// <param name="c_id">Initial value of the C_id property.</param>
        /// <param name="account_id">Initial value of the account_id property.</param>
        /// <param name="reason">Initial value of the reason property.</param>
        /// <param name="amount">Initial value of the amount property.</param>
        /// <param name="date_donated">Initial value of the date_donated property.</param>
        /// <param name="paid">Initial value of the paid property.</param>
        public static t_donations Createt_donations(global::System.Int32 c_id, global::System.Int32 account_id, global::System.String reason, global::System.Double amount, global::System.DateTime date_donated, global::System.Boolean paid)
        {
            t_donations t_donations = new t_donations();
            t_donations.C_id = c_id;
            t_donations.account_id = account_id;
            t_donations.reason = reason;
            t_donations.amount = amount;
            t_donations.date_donated = date_donated;
            t_donations.paid = paid;
            return t_donations;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 C_id
        {
            get
            {
                return _C_id;
            }
            set
            {
                if (_C_id != value)
                {
                    OnC_idChanging(value);
                    ReportPropertyChanging("C_id");
                    _C_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("C_id");
                    OnC_idChanged();
                }
            }
        }
        private global::System.Int32 _C_id;
        partial void OnC_idChanging(global::System.Int32 value);
        partial void OnC_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 account_id
        {
            get
            {
                return _account_id;
            }
            set
            {
                Onaccount_idChanging(value);
                ReportPropertyChanging("account_id");
                _account_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("account_id");
                Onaccount_idChanged();
            }
        }
        private global::System.Int32 _account_id;
        partial void Onaccount_idChanging(global::System.Int32 value);
        partial void Onaccount_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String reason
        {
            get
            {
                return _reason;
            }
            set
            {
                OnreasonChanging(value);
                ReportPropertyChanging("reason");
                _reason = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("reason");
                OnreasonChanged();
            }
        }
        private global::System.String _reason;
        partial void OnreasonChanging(global::System.String value);
        partial void OnreasonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double amount
        {
            get
            {
                return _amount;
            }
            set
            {
                OnamountChanging(value);
                ReportPropertyChanging("amount");
                _amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("amount");
                OnamountChanged();
            }
        }
        private global::System.Double _amount;
        partial void OnamountChanging(global::System.Double value);
        partial void OnamountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date_donated
        {
            get
            {
                return _date_donated;
            }
            set
            {
                Ondate_donatedChanging(value);
                ReportPropertyChanging("date_donated");
                _date_donated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_donated");
                Ondate_donatedChanged();
            }
        }
        private global::System.DateTime _date_donated;
        partial void Ondate_donatedChanging(global::System.DateTime value);
        partial void Ondate_donatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date_paid
        {
            get
            {
                return _date_paid;
            }
            set
            {
                Ondate_paidChanging(value);
                ReportPropertyChanging("date_paid");
                _date_paid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_paid");
                Ondate_paidChanged();
            }
        }
        private Nullable<global::System.DateTime> _date_paid;
        partial void Ondate_paidChanging(Nullable<global::System.DateTime> value);
        partial void Ondate_paidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean paid
        {
            get
            {
                return _paid;
            }
            set
            {
                OnpaidChanging(value);
                ReportPropertyChanging("paid");
                _paid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("paid");
                OnpaidChanged();
            }
        }
        private global::System.Boolean _paid;
        partial void OnpaidChanging(global::System.Boolean value);
        partial void OnpaidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String comments
        {
            get
            {
                return _comments;
            }
            set
            {
                OncommentsChanging(value);
                ReportPropertyChanging("comments");
                _comments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("comments");
                OncommentsChanged();
            }
        }
        private global::System.String _comments;
        partial void OncommentsChanging(global::System.String value);
        partial void OncommentsChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("zera_leviModel", "fk_donations_accounts", "t_accounts")]
        public t_accounts t_accounts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_accounts>("zera_leviModel.fk_donations_accounts", "t_accounts").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_accounts>("zera_leviModel.fk_donations_accounts", "t_accounts").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<t_accounts> t_accountsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_accounts>("zera_leviModel.fk_donations_accounts", "t_accounts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<t_accounts>("zera_leviModel.fk_donations_accounts", "t_accounts", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="zera_leviModel", Name="t_people")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_people : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new t_people object.
        /// </summary>
        /// <param name="c_id">Initial value of the C_id property.</param>
        public static t_people Createt_people(global::System.Int32 c_id)
        {
            t_people t_people = new t_people();
            t_people.C_id = c_id;
            return t_people;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 C_id
        {
            get
            {
                return _C_id;
            }
            set
            {
                if (_C_id != value)
                {
                    OnC_idChanging(value);
                    ReportPropertyChanging("C_id");
                    _C_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("C_id");
                    OnC_idChanged();
                }
            }
        }
        private global::System.Int32 _C_id;
        partial void OnC_idChanging(global::System.Int32 value);
        partial void OnC_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String given_name
        {
            get
            {
                return _given_name;
            }
            set
            {
                Ongiven_nameChanging(value);
                ReportPropertyChanging("given_name");
                _given_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("given_name");
                Ongiven_nameChanged();
            }
        }
        private global::System.String _given_name;
        partial void Ongiven_nameChanging(global::System.String value);
        partial void Ongiven_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String family_name
        {
            get
            {
                return _family_name;
            }
            set
            {
                Onfamily_nameChanging(value);
                ReportPropertyChanging("family_name");
                _family_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("family_name");
                Onfamily_nameChanged();
            }
        }
        private global::System.String _family_name;
        partial void Onfamily_nameChanging(global::System.String value);
        partial void Onfamily_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> member
        {
            get
            {
                return _member;
            }
            set
            {
                OnmemberChanging(value);
                ReportPropertyChanging("member");
                _member = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("member");
                OnmemberChanged();
            }
        }
        private Nullable<global::System.Boolean> _member;
        partial void OnmemberChanging(Nullable<global::System.Boolean> value);
        partial void OnmemberChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("zera_leviModel", "fk_accounts_people1", "t_accounts")]
        public EntityCollection<t_accounts> t_accounts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<t_accounts>("zera_leviModel.fk_accounts_people1", "t_accounts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<t_accounts>("zera_leviModel.fk_accounts_people1", "t_accounts", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("zera_leviModel", "fk_phone_numbers_people1", "t_phone_numbers")]
        public EntityCollection<t_phone_numbers> t_phone_numbers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<t_phone_numbers>("zera_leviModel.fk_phone_numbers_people1", "t_phone_numbers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<t_phone_numbers>("zera_leviModel.fk_phone_numbers_people1", "t_phone_numbers", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("zera_leviModel", "fk_yahrtziehts_people1", "t_yahrtziehts")]
        public EntityCollection<t_yahrtziehts> t_yahrtziehts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<t_yahrtziehts>("zera_leviModel.fk_yahrtziehts_people1", "t_yahrtziehts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<t_yahrtziehts>("zera_leviModel.fk_yahrtziehts_people1", "t_yahrtziehts", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="zera_leviModel", Name="t_phone_numbers")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_phone_numbers : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new t_phone_numbers object.
        /// </summary>
        /// <param name="person_id">Initial value of the person_id property.</param>
        /// <param name="number">Initial value of the number property.</param>
        /// <param name="number_type">Initial value of the number_type property.</param>
        /// <param name="c_id">Initial value of the C_id property.</param>
        public static t_phone_numbers Createt_phone_numbers(global::System.Int32 person_id, global::System.String number, global::System.Int32 number_type, global::System.Int32 c_id)
        {
            t_phone_numbers t_phone_numbers = new t_phone_numbers();
            t_phone_numbers.person_id = person_id;
            t_phone_numbers.number = number;
            t_phone_numbers.number_type = number_type;
            t_phone_numbers.C_id = c_id;
            return t_phone_numbers;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 person_id
        {
            get
            {
                return _person_id;
            }
            set
            {
                Onperson_idChanging(value);
                ReportPropertyChanging("person_id");
                _person_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("person_id");
                Onperson_idChanged();
            }
        }
        private global::System.Int32 _person_id;
        partial void Onperson_idChanging(global::System.Int32 value);
        partial void Onperson_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String number
        {
            get
            {
                return _number;
            }
            set
            {
                OnnumberChanging(value);
                ReportPropertyChanging("number");
                _number = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("number");
                OnnumberChanged();
            }
        }
        private global::System.String _number;
        partial void OnnumberChanging(global::System.String value);
        partial void OnnumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 number_type
        {
            get
            {
                return _number_type;
            }
            set
            {
                Onnumber_typeChanging(value);
                ReportPropertyChanging("number_type");
                _number_type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("number_type");
                Onnumber_typeChanged();
            }
        }
        private global::System.Int32 _number_type;
        partial void Onnumber_typeChanging(global::System.Int32 value);
        partial void Onnumber_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 C_id
        {
            get
            {
                return _C_id;
            }
            set
            {
                if (_C_id != value)
                {
                    OnC_idChanging(value);
                    ReportPropertyChanging("C_id");
                    _C_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("C_id");
                    OnC_idChanged();
                }
            }
        }
        private global::System.Int32 _C_id;
        partial void OnC_idChanging(global::System.Int32 value);
        partial void OnC_idChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("zera_leviModel", "fk_phone_numbers_people1", "t_people")]
        public t_people t_people
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_people>("zera_leviModel.fk_phone_numbers_people1", "t_people").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_people>("zera_leviModel.fk_phone_numbers_people1", "t_people").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<t_people> t_peopleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_people>("zera_leviModel.fk_phone_numbers_people1", "t_people");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<t_people>("zera_leviModel.fk_phone_numbers_people1", "t_people", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("zera_leviModel", "fk_phone_numbers_phone_types1", "t_phone_types")]
        public t_phone_types t_phone_types
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_phone_types>("zera_leviModel.fk_phone_numbers_phone_types1", "t_phone_types").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_phone_types>("zera_leviModel.fk_phone_numbers_phone_types1", "t_phone_types").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<t_phone_types> t_phone_typesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_phone_types>("zera_leviModel.fk_phone_numbers_phone_types1", "t_phone_types");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<t_phone_types>("zera_leviModel.fk_phone_numbers_phone_types1", "t_phone_types", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="zera_leviModel", Name="t_phone_types")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_phone_types : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new t_phone_types object.
        /// </summary>
        /// <param name="c_id">Initial value of the C_id property.</param>
        /// <param name="type_name">Initial value of the type_name property.</param>
        public static t_phone_types Createt_phone_types(global::System.Int32 c_id, global::System.String type_name)
        {
            t_phone_types t_phone_types = new t_phone_types();
            t_phone_types.C_id = c_id;
            t_phone_types.type_name = type_name;
            return t_phone_types;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 C_id
        {
            get
            {
                return _C_id;
            }
            set
            {
                if (_C_id != value)
                {
                    OnC_idChanging(value);
                    ReportPropertyChanging("C_id");
                    _C_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("C_id");
                    OnC_idChanged();
                }
            }
        }
        private global::System.Int32 _C_id;
        partial void OnC_idChanging(global::System.Int32 value);
        partial void OnC_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String type_name
        {
            get
            {
                return _type_name;
            }
            set
            {
                Ontype_nameChanging(value);
                ReportPropertyChanging("type_name");
                _type_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("type_name");
                Ontype_nameChanged();
            }
        }
        private global::System.String _type_name;
        partial void Ontype_nameChanging(global::System.String value);
        partial void Ontype_nameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("zera_leviModel", "fk_phone_numbers_phone_types1", "t_phone_numbers")]
        public EntityCollection<t_phone_numbers> t_phone_numbers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<t_phone_numbers>("zera_leviModel.fk_phone_numbers_phone_types1", "t_phone_numbers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<t_phone_numbers>("zera_leviModel.fk_phone_numbers_phone_types1", "t_phone_numbers", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="zera_leviModel", Name="t_privilege_groups")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_privilege_groups : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new t_privilege_groups object.
        /// </summary>
        /// <param name="c_id">Initial value of the C_id property.</param>
        public static t_privilege_groups Createt_privilege_groups(global::System.Int32 c_id)
        {
            t_privilege_groups t_privilege_groups = new t_privilege_groups();
            t_privilege_groups.C_id = c_id;
            return t_privilege_groups;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 C_id
        {
            get
            {
                return _C_id;
            }
            set
            {
                if (_C_id != value)
                {
                    OnC_idChanging(value);
                    ReportPropertyChanging("C_id");
                    _C_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("C_id");
                    OnC_idChanged();
                }
            }
        }
        private global::System.Int32 _C_id;
        partial void OnC_idChanging(global::System.Int32 value);
        partial void OnC_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String group_name
        {
            get
            {
                return _group_name;
            }
            set
            {
                Ongroup_nameChanging(value);
                ReportPropertyChanging("group_name");
                _group_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("group_name");
                Ongroup_nameChanged();
            }
        }
        private global::System.String _group_name;
        partial void Ongroup_nameChanging(global::System.String value);
        partial void Ongroup_nameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("zera_leviModel", "fk_users_privilege_groups1", "t_users")]
        public EntityCollection<t_users> t_users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<t_users>("zera_leviModel.fk_users_privilege_groups1", "t_users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<t_users>("zera_leviModel.fk_users_privilege_groups1", "t_users", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("zera_leviModel", "t_privileges_per_group", "t_privileges")]
        public EntityCollection<t_privileges> t_privileges
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<t_privileges>("zera_leviModel.t_privileges_per_group", "t_privileges");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<t_privileges>("zera_leviModel.t_privileges_per_group", "t_privileges", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="zera_leviModel", Name="t_privileges")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_privileges : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new t_privileges object.
        /// </summary>
        /// <param name="c_id">Initial value of the C_id property.</param>
        public static t_privileges Createt_privileges(global::System.Int32 c_id)
        {
            t_privileges t_privileges = new t_privileges();
            t_privileges.C_id = c_id;
            return t_privileges;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 C_id
        {
            get
            {
                return _C_id;
            }
            set
            {
                if (_C_id != value)
                {
                    OnC_idChanging(value);
                    ReportPropertyChanging("C_id");
                    _C_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("C_id");
                    OnC_idChanged();
                }
            }
        }
        private global::System.Int32 _C_id;
        partial void OnC_idChanging(global::System.Int32 value);
        partial void OnC_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String privilege_name
        {
            get
            {
                return _privilege_name;
            }
            set
            {
                Onprivilege_nameChanging(value);
                ReportPropertyChanging("privilege_name");
                _privilege_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("privilege_name");
                Onprivilege_nameChanged();
            }
        }
        private global::System.String _privilege_name;
        partial void Onprivilege_nameChanging(global::System.String value);
        partial void Onprivilege_nameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("zera_leviModel", "t_privileges_per_group", "t_privilege_groups")]
        public EntityCollection<t_privilege_groups> t_privilege_groups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<t_privilege_groups>("zera_leviModel.t_privileges_per_group", "t_privilege_groups");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<t_privilege_groups>("zera_leviModel.t_privileges_per_group", "t_privilege_groups", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="zera_leviModel", Name="t_users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new t_users object.
        /// </summary>
        /// <param name="c_id">Initial value of the C_id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="password">Initial value of the password property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="privileges_group">Initial value of the privileges_group property.</param>
        public static t_users Createt_users(global::System.Int32 c_id, global::System.String name, global::System.String password, global::System.String email, global::System.Int32 privileges_group)
        {
            t_users t_users = new t_users();
            t_users.C_id = c_id;
            t_users.name = name;
            t_users.password = password;
            t_users.email = email;
            t_users.privileges_group = privileges_group;
            return t_users;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 C_id
        {
            get
            {
                return _C_id;
            }
            set
            {
                if (_C_id != value)
                {
                    OnC_idChanging(value);
                    ReportPropertyChanging("C_id");
                    _C_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("C_id");
                    OnC_idChanged();
                }
            }
        }
        private global::System.Int32 _C_id;
        partial void OnC_idChanging(global::System.Int32 value);
        partial void OnC_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 privileges_group
        {
            get
            {
                return _privileges_group;
            }
            set
            {
                Onprivileges_groupChanging(value);
                ReportPropertyChanging("privileges_group");
                _privileges_group = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("privileges_group");
                Onprivileges_groupChanged();
            }
        }
        private global::System.Int32 _privileges_group;
        partial void Onprivileges_groupChanging(global::System.Int32 value);
        partial void Onprivileges_groupChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("zera_leviModel", "fk_users_privilege_groups1", "t_privilege_groups")]
        public t_privilege_groups t_privilege_groups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_privilege_groups>("zera_leviModel.fk_users_privilege_groups1", "t_privilege_groups").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_privilege_groups>("zera_leviModel.fk_users_privilege_groups1", "t_privilege_groups").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<t_privilege_groups> t_privilege_groupsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_privilege_groups>("zera_leviModel.fk_users_privilege_groups1", "t_privilege_groups");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<t_privilege_groups>("zera_leviModel.fk_users_privilege_groups1", "t_privilege_groups", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="zera_leviModel", Name="t_yahrtziehts")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_yahrtziehts : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new t_yahrtziehts object.
        /// </summary>
        /// <param name="c_id">Initial value of the C_id property.</param>
        /// <param name="person_id">Initial value of the person_id property.</param>
        /// <param name="date">Initial value of the date property.</param>
        /// <param name="deceaseds_name">Initial value of the deceaseds_name property.</param>
        public static t_yahrtziehts Createt_yahrtziehts(global::System.Int32 c_id, global::System.Int32 person_id, global::System.DateTime date, global::System.String deceaseds_name)
        {
            t_yahrtziehts t_yahrtziehts = new t_yahrtziehts();
            t_yahrtziehts.C_id = c_id;
            t_yahrtziehts.person_id = person_id;
            t_yahrtziehts.date = date;
            t_yahrtziehts.deceaseds_name = deceaseds_name;
            return t_yahrtziehts;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 C_id
        {
            get
            {
                return _C_id;
            }
            set
            {
                if (_C_id != value)
                {
                    OnC_idChanging(value);
                    ReportPropertyChanging("C_id");
                    _C_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("C_id");
                    OnC_idChanged();
                }
            }
        }
        private global::System.Int32 _C_id;
        partial void OnC_idChanging(global::System.Int32 value);
        partial void OnC_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 person_id
        {
            get
            {
                return _person_id;
            }
            set
            {
                Onperson_idChanging(value);
                ReportPropertyChanging("person_id");
                _person_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("person_id");
                Onperson_idChanged();
            }
        }
        private global::System.Int32 _person_id;
        partial void Onperson_idChanging(global::System.Int32 value);
        partial void Onperson_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String relation
        {
            get
            {
                return _relation;
            }
            set
            {
                OnrelationChanging(value);
                ReportPropertyChanging("relation");
                _relation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("relation");
                OnrelationChanged();
            }
        }
        private global::System.String _relation;
        partial void OnrelationChanging(global::System.String value);
        partial void OnrelationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.DateTime _date;
        partial void OndateChanging(global::System.DateTime value);
        partial void OndateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String deceaseds_name
        {
            get
            {
                return _deceaseds_name;
            }
            set
            {
                Ondeceaseds_nameChanging(value);
                ReportPropertyChanging("deceaseds_name");
                _deceaseds_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("deceaseds_name");
                Ondeceaseds_nameChanged();
            }
        }
        private global::System.String _deceaseds_name;
        partial void Ondeceaseds_nameChanging(global::System.String value);
        partial void Ondeceaseds_nameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("zera_leviModel", "fk_yahrtziehts_people1", "t_people")]
        public t_people t_people
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_people>("zera_leviModel.fk_yahrtziehts_people1", "t_people").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_people>("zera_leviModel.fk_yahrtziehts_people1", "t_people").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<t_people> t_peopleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<t_people>("zera_leviModel.fk_yahrtziehts_people1", "t_people");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<t_people>("zera_leviModel.fk_yahrtziehts_people1", "t_people", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
